### PR TITLE
Add mailchimp

### PR DESCRIPTION
**Pull request by fakhamatia**
Add `mailchimp.com`
Add `list-manage.com`
Remove duplicate domains
And Sort domains

### CODE REVIEW

**Comment by aminvakil** [comment]
May I ask what is the purpose of sorting domains?

**Comment by fakhamatia** [comment]
> May I ask what is the purpose of sorting domains?

The purpose is its appearance
Is there a problem with the order of the domains?

**Comment by aminvakil** [comment]
> > May I ask what is the purpose of sorting domains?
> 
> The purpose is its appearance

Its appearance is fine for me :)
> Is there a problem with the order of the domains?

Also people (including me) rely on this order as it shows how it has been changed over time and what was added in time, I don't see any benefit from sorting the list, although I don't maintain the list and maintainers may disagree.

**Comment by behdad222** [comment]
@aminvakil 
Domain position is not a good measure of when to add to a list.

**Pull request closed without merging**
